apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
#        image: gcr.io/${PROJECT_ID}/backend:latest
        image: gcr.io/microservices-k8s-demo-460710/backend:latest

        env:
          - name: BACKEND_PORT
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: BACKEND_PORT

        ports:
        - containerPort: BACKEND_PORT
          # Note: BACKEND_PORT is defined in the ConfigMap, so it should be set to the value from the ConfigMap.
          # If you want to use a specific port, you can replace BACKEND_PORT with the actual port number.
          # For example, if BACKEND_PORT is 8080, you can set containerPort: 8080.

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
