steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/echo:latest', '-f', 'echo/Dockerfile', 'echo' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/echo:latest' ]
images:
  - 'gcr.io/$PROJECT_ID/echo:latest'